<a href="./index.php" <?php if($current_page == 'index.php') echo 'class="active"'; ?>>Home</a>
<a href="./jobs.php" <?php if($current_page == 'jobs.php') echo 'class="active"'; ?>>Jobs</a>
<a href="./about.php" <?php if($current_page == 'about.php') echo 'class="active"'; ?>>About</a>
<a href="./enhancements.php" <?php if($current_page == 'enhancements.php') echo 'class="active"'; ?>>Enhancements</a>
<a href="./enhancements2.php" <?php if($current_page == 'enhancements2.php') echo 'class="active"'; ?>>Enhancements2</a>
<a href="./phpenhancements.php" <?php if($current_page == 'phpenhancements.php') echo 'class="active"'; ?>>PHP Enhancements</a>
<a class="btn" href="./apply.php">Apply Jobs →</a>
